apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: my-database
  namespace: database
spec:
  selector:
    matchLabels:
      app: mysql
      tier: mysql
  template:
    metadata:
      labels:
        app: my-database
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db_pass
              key: db-secret
        - name: MYSQL_Username
          valueFrom:
            secretKeyRef:
              name: db_user
              key: db-secret
        ports:
        - containerPort: 3306
          name: mysql
